# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :hw12 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.111',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
          box.vm.provision "prepare", type: "shell" do |s|
            s.inline = "yum install -y epel-release python3"
          end
          box.vm.provision "task-1", type: "shell", path: "./provision/task-01.sh"
          box.vm.provision "task-2", type: "shell", path: "./provision/task-02.sh"
          box.vm.provision "task-3", type: "shell", path: "./provision/task-03.sh"
    
      end
  end
end