---
# tasks file for roles/nginx
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present

- name: Install packages
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ nginx_host_packages }}'
  tags:
    - selinux-packages

- name: NGINX | Install nginx package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name: NGINX | Create NGINX config from template
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-config