---
all:
  children:
    borg:
  vars:
    ansible_user: 'vagrant'
    
borg:
  hosts:
    backup-server:
      ansible_host: 192.168.56.101
      ansible_ssh_private_key_file: ".vagrant/machines/backup-server/virtualbox/private_key"
    client:
      ansible_host: 192.168.56.102
      ansible_ssh_private_key_file: ".vagrant/machines/client/virtualbox/private_key"