---
# tasks file for rsyslog-client
- name: Set rsyslog config
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    mode: '0644'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-config

- name: Copy auditd config file
  copy:
    src: auditd.conf
    dest: /etc/audit/auditd.conf
    mode: '0640'
  notify:
    - restart auditd
  tags:
    - auditd-config